<?php

/**
 * @file
 * Contains youtube_playlist_import.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function youtube_playlist_import_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the youtube_playlist_import module.
    case 'help.page.youtube_playlist_import':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Import Youtube playlists as standalone Youtube video Media entities.') . '</p>';
      return $output;

    default:
  }
}
